// HTTP Status Codes
export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
} as const;

// Validation Limits
export const VALIDATION_LIMITS = {
    MAX_PROPERTY_NAME_LENGTH: 200,
    MAX_STRING_LENGTH: 50000,
    MAX_ARRAY_STRING_LENGTH: 10000,
    MAX_NESTED_OBJECT_DEPTH: 20,
    MAX_ARRAY_ITEMS: 1000,
    MAX_NESTED_PROPERTY_NAME_LENGTH: 100,
    MAX_NESTED_STRING_LENGTH: 10000,
    MAX_NESTED_ARRAY_ITEMS: 100,
    MAX_NESTED_OBJECT_PROPERTIES: 100,
    MAX_ROOT_OBJECT_PROPERTIES: 500,
    MAX_DOCUMENT_DEPTH: 10,
    DOCUMENT_PREVIEW_LENGTH: 100,
    MAX_DISPLAY_NAME_LENGTH: 50,
    MAX_GROUP_NAME_LENGTH: 100,
    MAX_GROUP_DESCRIPTION_LENGTH: 500,
    MAX_GROUP_MEMBERS: 50,
} as const;

// Rate Limiting & Performance
export const RATE_LIMITS = {
    WINDOW_MS: 60000,
    PROD_MAX_REQUESTS: 10,
    DEV_MAX_REQUESTS: 10000,
    CLEANUP_INTERVAL_MS: 60000,
    CLEANUP_MULTIPLIER: 2,
    CLEANUP_BATCH_SIZE: 100,
    PROD_SLOW_REQUEST_MS: 1000,
    DEV_SLOW_REQUEST_MS: 5000,
    HEALTH_CHECK_TIMEOUT_MS: 5000,
} as const;

// Document Configuration
export const DOCUMENT_CONFIG = {
    LIST_LIMIT: 100,
    PREVIEW_LENGTH: 100,
    PAGINATION_EXTRA_ITEM: 1,
    PROD_MAX_STRING_LENGTH: 50000,
    DEV_MAX_STRING_LENGTH: 100000,
    PROD_MAX_PROPERTY_COUNT: 500,
    DEV_MAX_PROPERTY_COUNT: 1000,
} as const;

// Authentication
export const AUTH = {
    BEARER_TOKEN_PREFIX_LENGTH: 7,
    TOKEN_LOG_PREFIX_LENGTH: 10,
} as const;

// System Constants
export const SYSTEM = {
    BYTES_PER_KB: 1024,
    AUTH_LIST_LIMIT: 1,
} as const;
