import type { AnyFieldDef } from './field-types';

export const FIELD_REGISTRY: readonly AnyFieldDef[] = [
    // ===== PALETTE COLORS =====
    {
        key: 'primaryColor',
        type: 'color',
        label: 'Primary',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.primary',
        testId: 'primary-color-input',
        gridCols: 2,
    },
    {
        key: 'primaryVariantColor',
        type: 'color',
        label: 'Primary Variant',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.primaryVariant',
        testId: 'primary-variant-color-input',
        gridCols: 2,
    },
    {
        key: 'secondaryColor',
        type: 'color',
        label: 'Secondary',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.secondary',
        testId: 'secondary-color-input',
        gridCols: 2,
    },
    {
        key: 'secondaryVariantColor',
        type: 'color',
        label: 'Secondary Variant',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.secondaryVariant',
        testId: 'secondary-variant-color-input',
        gridCols: 2,
    },
    {
        key: 'accentColor',
        type: 'color',
        label: 'Accent',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.accent',
        testId: 'accent-color-input',
        gridCols: 1,
    },
    {
        key: 'neutralColor',
        type: 'color',
        label: 'Neutral',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.neutral',
        testId: 'neutral-color-input',
        gridCols: 2,
    },
    {
        key: 'neutralVariantColor',
        type: 'color',
        label: 'Neutral Variant',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.neutralVariant',
        testId: 'neutral-variant-color-input',
        gridCols: 2,
    },
    {
        key: 'successColor',
        type: 'color',
        label: 'Success',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.success',
        testId: 'success-color-input',
        gridCols: 2,
    },
    {
        key: 'warningColor',
        type: 'color',
        label: 'Warning',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.warning',
        testId: 'warning-color-input',
        gridCols: 2,
    },
    {
        key: 'dangerColor',
        type: 'color',
        label: 'Danger',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.danger',
        testId: 'danger-color-input',
        gridCols: 2,
    },
    {
        key: 'infoColor',
        type: 'color',
        label: 'Info',
        section: 'palette',
        required: true,
        default: '',
        tokenPath: 'palette.info',
        testId: 'info-color-input',
        gridCols: 2,
    },

    // ===== SURFACE COLORS =====
    {
        key: 'surfaceBaseColor',
        type: 'color',
        label: 'Base',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.base',
        testId: 'surface-base-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceRaisedColor',
        type: 'color',
        label: 'Raised',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.raised',
        testId: 'surface-raised-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceSunkenColor',
        type: 'color',
        label: 'Sunken',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.sunken',
        testId: 'surface-sunken-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceOverlayColor',
        type: 'rgba',
        label: 'Overlay (rgba)',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.overlay',
        testId: 'surface-overlay-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceWarningColor',
        type: 'color',
        label: 'Warning',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.warning',
        testId: 'surface-warning-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceMutedColor',
        type: 'color',
        label: 'Muted',
        section: 'surfaces',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.surface.muted',
        testId: 'surface-muted-color-input',
        gridCols: 2,
    },
    {
        key: 'surfaceSubtleColor',
        type: 'color',
        label: 'Subtle',
        section: 'surfaces',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.surface.subtle',
        testId: 'surface-subtle-color-input',
        gridCols: 2,
    },
    {
        key: 'surfacePopoverColor',
        type: 'color',
        label: 'Popover',
        section: 'surfaces',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.surface.popover',
        testId: 'surface-popover-color-input',
        gridCols: 2,
    },

    // ===== TEXT COLORS =====
    {
        key: 'textPrimaryColor',
        type: 'color',
        label: 'Primary',
        section: 'text',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.text.primary',
        testId: 'text-primary-color-input',
        gridCols: 2,
    },
    {
        key: 'textSecondaryColor',
        type: 'color',
        label: 'Secondary',
        section: 'text',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.text.secondary',
        testId: 'text-secondary-color-input',
        gridCols: 2,
    },
    {
        key: 'textMutedColor',
        type: 'color',
        label: 'Muted',
        section: 'text',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.text.muted',
        testId: 'text-muted-color-input',
        gridCols: 2,
    },
    {
        key: 'textInvertedColor',
        type: 'color',
        label: 'Inverted',
        section: 'text',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.text.inverted',
        testId: 'text-inverted-color-input',
        gridCols: 2,
    },
    {
        key: 'textAccentColor',
        type: 'color',
        label: 'Accent',
        section: 'text',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.text.accent',
        testId: 'text-accent-color-input',
        gridCols: 2,
    },

    // ===== INTERACTIVE COLORS - Primary =====
    {
        key: 'interactivePrimaryColor',
        type: 'color',
        label: 'Default',
        section: 'interactive',
        subsection: 'Primary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.primary',
        testId: 'interactive-primary-color-input',
        gridCols: 2,
    },
    {
        key: 'interactivePrimaryHoverColor',
        type: 'color',
        label: 'Hover',
        section: 'interactive',
        subsection: 'Primary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.primaryHover',
        testId: 'interactive-primary-hover-color-input',
        gridCols: 2,
    },
    {
        key: 'interactivePrimaryActiveColor',
        type: 'color',
        label: 'Active',
        section: 'interactive',
        subsection: 'Primary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.primaryActive',
        testId: 'interactive-primary-active-color-input',
        gridCols: 2,
    },
    {
        key: 'interactivePrimaryForegroundColor',
        type: 'color',
        label: 'Foreground',
        section: 'interactive',
        subsection: 'Primary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.primaryForeground',
        testId: 'interactive-primary-foreground-color-input',
        gridCols: 2,
    },

    // ===== INTERACTIVE COLORS - Secondary =====
    {
        key: 'interactiveSecondaryColor',
        type: 'color',
        label: 'Default',
        section: 'interactive',
        subsection: 'Secondary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.secondary',
        testId: 'interactive-secondary-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveSecondaryHoverColor',
        type: 'color',
        label: 'Hover',
        section: 'interactive',
        subsection: 'Secondary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.secondaryHover',
        testId: 'interactive-secondary-hover-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveSecondaryActiveColor',
        type: 'color',
        label: 'Active',
        section: 'interactive',
        subsection: 'Secondary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.secondaryActive',
        testId: 'interactive-secondary-active-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveSecondaryForegroundColor',
        type: 'color',
        label: 'Foreground',
        section: 'interactive',
        subsection: 'Secondary',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.secondaryForeground',
        testId: 'interactive-secondary-foreground-color-input',
        gridCols: 2,
    },

    // ===== INTERACTIVE COLORS - Accent =====
    {
        key: 'interactiveAccentColor',
        type: 'color',
        label: 'Accent',
        section: 'interactive',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.accent',
        testId: 'interactive-accent-color-input',
        gridCols: 1,
    },

    // ===== INTERACTIVE COLORS - Destructive =====
    {
        key: 'interactiveDestructiveColor',
        type: 'color',
        label: 'Default',
        section: 'interactive',
        subsection: 'Destructive',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.destructive',
        testId: 'interactive-destructive-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveDestructiveHoverColor',
        type: 'color',
        label: 'Hover',
        section: 'interactive',
        subsection: 'Destructive',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.destructiveHover',
        testId: 'interactive-destructive-hover-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveDestructiveActiveColor',
        type: 'color',
        label: 'Active',
        section: 'interactive',
        subsection: 'Destructive',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.destructiveActive',
        testId: 'interactive-destructive-active-color-input',
        gridCols: 2,
    },
    {
        key: 'interactiveDestructiveForegroundColor',
        type: 'color',
        label: 'Foreground',
        section: 'interactive',
        subsection: 'Destructive',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.interactive.destructiveForeground',
        testId: 'interactive-destructive-foreground-color-input',
        gridCols: 2,
    },

    // ===== INTERACTIVE COLORS - Effects (optional) =====
    {
        key: 'interactiveGhostColor',
        type: 'color',
        label: 'Ghost',
        section: 'interactive',
        subsection: 'Effects (optional)',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.interactive.ghost',
        testId: 'interactive-ghost-color-input',
        gridCols: 3,
    },
    {
        key: 'interactiveMagneticColor',
        type: 'color',
        label: 'Magnetic',
        section: 'interactive',
        subsection: 'Effects (optional)',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.interactive.magnetic',
        testId: 'interactive-magnetic-color-input',
        gridCols: 3,
    },
    {
        key: 'interactiveGlowColor',
        type: 'color',
        label: 'Glow',
        section: 'interactive',
        subsection: 'Effects (optional)',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.interactive.glow',
        testId: 'interactive-glow-color-input',
        gridCols: 3,
    },

    // ===== BORDER COLORS =====
    {
        key: 'borderSubtleColor',
        type: 'color',
        label: 'Subtle',
        section: 'border',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.border.subtle',
        testId: 'border-subtle-color-input',
        gridCols: 2,
    },
    {
        key: 'borderDefaultColor',
        type: 'color',
        label: 'Default',
        section: 'border',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.border.default',
        testId: 'border-default-color-input',
        gridCols: 2,
    },
    {
        key: 'borderStrongColor',
        type: 'color',
        label: 'Strong',
        section: 'border',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.border.strong',
        testId: 'border-strong-color-input',
        gridCols: 2,
    },
    {
        key: 'borderFocusColor',
        type: 'color',
        label: 'Focus',
        section: 'border',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.border.focus',
        testId: 'border-focus-color-input',
        gridCols: 2,
    },
    {
        key: 'borderWarningColor',
        type: 'color',
        label: 'Warning',
        section: 'border',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.border.warning',
        testId: 'border-warning-color-input',
        gridCols: 2,
    },

    // ===== STATUS COLORS =====
    {
        key: 'statusSuccessColor',
        type: 'color',
        label: 'Success',
        section: 'status',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.status.success',
        testId: 'status-success-color-input',
        gridCols: 2,
    },
    {
        key: 'statusWarningColor',
        type: 'color',
        label: 'Warning',
        section: 'status',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.status.warning',
        testId: 'status-warning-color-input',
        gridCols: 2,
    },
    {
        key: 'statusDangerColor',
        type: 'color',
        label: 'Danger',
        section: 'status',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.status.danger',
        testId: 'status-danger-color-input',
        gridCols: 2,
    },
    {
        key: 'statusInfoColor',
        type: 'color',
        label: 'Info',
        section: 'status',
        required: true,
        default: '',
        tokenPath: 'semantics.colors.status.info',
        testId: 'status-info-color-input',
        gridCols: 2,
    },

    // ===== TYPOGRAPHY - Font Families =====
    {
        key: 'fontFamilySans',
        type: 'string',
        label: 'Sans',
        section: 'typography',
        subsection: 'Font Families',
        required: true,
        default: '',
        tokenPath: 'typography.fontFamily.sans',
        placeholder: 'Inter, system-ui',
        gridCols: 3,
    },
    {
        key: 'fontFamilySerif',
        type: 'string',
        label: 'Serif',
        section: 'typography',
        subsection: 'Font Families',
        required: false,
        default: '',
        tokenPath: 'typography.fontFamily.serif',
        placeholder: 'Georgia, serif',
        gridCols: 3,
    },
    {
        key: 'fontFamilyMono',
        type: 'string',
        label: 'Mono',
        section: 'typography',
        subsection: 'Font Families',
        required: true,
        default: '',
        tokenPath: 'typography.fontFamily.mono',
        placeholder: 'Monaco, monospace',
        gridCols: 3,
    },

    // ===== TYPOGRAPHY - Sizes =====
    {
        key: 'typographySizeXs',
        type: 'string',
        label: 'XS',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.xs',
        placeholder: '0.75rem',
        monospace: true,
        gridCols: 5,
    },
    {
        key: 'typographySizeSm',
        type: 'string',
        label: 'SM',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.sm',
        placeholder: '0.875rem',
        monospace: true,
        gridCols: 5,
    },
    {
        key: 'typographySizeMd',
        type: 'string',
        label: 'MD',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.md',
        placeholder: '1rem',
        monospace: true,
        gridCols: 5,
    },
    {
        key: 'typographySizeLg',
        type: 'string',
        label: 'LG',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.lg',
        placeholder: '1.125rem',
        monospace: true,
        gridCols: 5,
    },
    {
        key: 'typographySizeXl',
        type: 'string',
        label: 'XL',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.xl',
        placeholder: '1.25rem',
        monospace: true,
        gridCols: 5,
    },
    {
        key: 'typographySize2xl',
        type: 'string',
        label: '2XL',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.2xl',
        placeholder: '1.5rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'typographySize3xl',
        type: 'string',
        label: '3XL',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.3xl',
        placeholder: '1.875rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'typographySize4xl',
        type: 'string',
        label: '4XL',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.4xl',
        placeholder: '2.25rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'typographySize5xl',
        type: 'string',
        label: '5XL',
        section: 'typography',
        subsection: 'Sizes (rem)',
        required: true,
        default: '',
        tokenPath: 'typography.sizes.5xl',
        placeholder: '3rem',
        monospace: true,
        gridCols: 4,
    },

    // ===== TYPOGRAPHY - Weights =====
    {
        key: 'fontWeightRegular',
        type: 'number',
        label: 'Regular',
        section: 'typography',
        subsection: 'Weights',
        required: true,
        default: 0,
        tokenPath: 'typography.weights.regular',
        placeholder: '400',
        gridCols: 4,
    },
    {
        key: 'fontWeightMedium',
        type: 'number',
        label: 'Medium',
        section: 'typography',
        subsection: 'Weights',
        required: true,
        default: 0,
        tokenPath: 'typography.weights.medium',
        placeholder: '500',
        gridCols: 4,
    },
    {
        key: 'fontWeightSemibold',
        type: 'number',
        label: 'Semibold',
        section: 'typography',
        subsection: 'Weights',
        required: true,
        default: 0,
        tokenPath: 'typography.weights.semibold',
        placeholder: '600',
        gridCols: 4,
    },
    {
        key: 'fontWeightBold',
        type: 'number',
        label: 'Bold',
        section: 'typography',
        subsection: 'Weights',
        required: true,
        default: 0,
        tokenPath: 'typography.weights.bold',
        placeholder: '700',
        gridCols: 4,
    },

    // ===== TYPOGRAPHY - Line Heights =====
    {
        key: 'lineHeightCompact',
        type: 'string',
        label: 'Compact',
        section: 'typography',
        subsection: 'Line Heights',
        required: true,
        default: '',
        tokenPath: 'typography.lineHeights.compact',
        placeholder: '1.25rem',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'lineHeightStandard',
        type: 'string',
        label: 'Standard',
        section: 'typography',
        subsection: 'Line Heights',
        required: true,
        default: '',
        tokenPath: 'typography.lineHeights.standard',
        placeholder: '1.5rem',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'lineHeightSpacious',
        type: 'string',
        label: 'Spacious',
        section: 'typography',
        subsection: 'Line Heights',
        required: true,
        default: '',
        tokenPath: 'typography.lineHeights.spacious',
        placeholder: '1.75rem',
        monospace: true,
        gridCols: 3,
    },

    // ===== TYPOGRAPHY - Letter Spacing =====
    {
        key: 'letterSpacingTight',
        type: 'string',
        label: 'Tight',
        section: 'typography',
        subsection: 'Letter Spacing',
        required: true,
        default: '',
        tokenPath: 'typography.letterSpacing.tight',
        placeholder: '-0.02rem',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'letterSpacingNormal',
        type: 'string',
        label: 'Normal',
        section: 'typography',
        subsection: 'Letter Spacing',
        required: true,
        default: '',
        tokenPath: 'typography.letterSpacing.normal',
        placeholder: '0rem',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'letterSpacingWide',
        type: 'string',
        label: 'Wide',
        section: 'typography',
        subsection: 'Letter Spacing',
        required: true,
        default: '',
        tokenPath: 'typography.letterSpacing.wide',
        placeholder: '0.02rem',
        monospace: true,
        gridCols: 3,
    },

    // ===== TYPOGRAPHY - Semantic Sizes =====
    {
        key: 'typographySemanticBody',
        type: 'select',
        label: 'Body',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.body',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        gridCols: 4,
    },
    {
        key: 'typographySemanticBodyStrong',
        type: 'select',
        label: 'Body Strong',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.bodyStrong',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        gridCols: 4,
    },
    {
        key: 'typographySemanticCaption',
        type: 'select',
        label: 'Caption',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.caption',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        gridCols: 4,
    },
    {
        key: 'typographySemanticButton',
        type: 'select',
        label: 'Button',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.button',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        gridCols: 4,
    },
    {
        key: 'typographySemanticEyebrow',
        type: 'select',
        label: 'Eyebrow',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.eyebrow',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        gridCols: 3,
    },
    {
        key: 'typographySemanticHeading',
        type: 'select',
        label: 'Heading',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.heading',
        options: ['xl', '2xl', '3xl', '4xl', '5xl'],
        gridCols: 3,
    },
    {
        key: 'typographySemanticDisplay',
        type: 'select',
        label: 'Display',
        section: 'typography',
        subsection: 'Semantic Sizes',
        required: true,
        default: '',
        tokenPath: 'typography.semantics.display',
        options: ['2xl', '3xl', '4xl', '5xl'],
        gridCols: 3,
    },

    // ===== SPACING - Base Scale =====
    {
        key: 'spacing2xs',
        type: 'string',
        label: '2XS',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.2xs',
        placeholder: '0.25rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacingXs',
        type: 'string',
        label: 'XS',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.xs',
        placeholder: '0.5rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacingSm',
        type: 'string',
        label: 'SM',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.sm',
        placeholder: '0.75rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacingMd',
        type: 'string',
        label: 'MD',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.md',
        placeholder: '1rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacingLg',
        type: 'string',
        label: 'LG',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.lg',
        placeholder: '1.5rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacingXl',
        type: 'string',
        label: 'XL',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.xl',
        placeholder: '2rem',
        monospace: true,
        gridCols: 4,
    },
    {
        key: 'spacing2xl',
        type: 'string',
        label: '2XL',
        section: 'spacing',
        subsection: 'Base Scale',
        required: true,
        default: '',
        tokenPath: 'spacing.2xl',
        placeholder: '3rem',
        monospace: true,
        gridCols: 4,
    },

    // ===== SPACING - Semantic =====
    {
        key: 'spacingPagePadding',
        type: 'string',
        label: 'Page Padding',
        section: 'spacing',
        subsection: 'Semantic',
        required: true,
        default: '',
        tokenPath: 'semantics.spacing.pagePadding',
        placeholder: '1.5rem',
        monospace: true,
        gridCols: 2,
    },
    {
        key: 'spacingSectionGap',
        type: 'string',
        label: 'Section Gap',
        section: 'spacing',
        subsection: 'Semantic',
        required: true,
        default: '',
        tokenPath: 'semantics.spacing.sectionGap',
        placeholder: '2rem',
        monospace: true,
        gridCols: 2,
    },
    {
        key: 'spacingCardPadding',
        type: 'string',
        label: 'Card Padding',
        section: 'spacing',
        subsection: 'Semantic',
        required: true,
        default: '',
        tokenPath: 'semantics.spacing.cardPadding',
        placeholder: '1rem',
        monospace: true,
        gridCols: 2,
    },
    {
        key: 'spacingComponentGap',
        type: 'string',
        label: 'Component Gap',
        section: 'spacing',
        subsection: 'Semantic',
        required: true,
        default: '',
        tokenPath: 'semantics.spacing.componentGap',
        placeholder: '0.5rem',
        monospace: true,
        gridCols: 2,
    },

    // ===== RADII =====
    {
        key: 'radiiNone',
        type: 'string',
        label: 'None',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.none',
        placeholder: '0px',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'radiiSm',
        type: 'string',
        label: 'SM',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.sm',
        placeholder: '4px',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'radiiMd',
        type: 'string',
        label: 'MD',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.md',
        placeholder: '8px',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'radiiLg',
        type: 'string',
        label: 'LG',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.lg',
        placeholder: '12px',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'radiiPill',
        type: 'string',
        label: 'Pill',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.pill',
        placeholder: '9999px',
        monospace: true,
        gridCols: 3,
    },
    {
        key: 'radiiFull',
        type: 'string',
        label: 'Full',
        section: 'radii',
        required: true,
        default: '',
        tokenPath: 'radii.full',
        placeholder: '9999px',
        monospace: true,
        gridCols: 3,
    },

    // ===== SHADOWS =====
    {
        key: 'shadowSm',
        type: 'string',
        label: 'SM',
        section: 'shadows',
        required: true,
        default: '',
        tokenPath: 'shadows.sm',
        placeholder: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        gridCols: 1,
    },
    {
        key: 'shadowMd',
        type: 'string',
        label: 'MD',
        section: 'shadows',
        required: true,
        default: '',
        tokenPath: 'shadows.md',
        placeholder: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        gridCols: 1,
    },
    {
        key: 'shadowLg',
        type: 'string',
        label: 'LG',
        section: 'shadows',
        required: true,
        default: '',
        tokenPath: 'shadows.lg',
        placeholder: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        gridCols: 1,
    },

    // ===== MOTION - Feature Flags =====
    {
        key: 'enableParallax',
        type: 'boolean',
        label: 'Parallax / Aurora Background',
        section: 'motion',
        subsection: 'Feature Flags',
        required: false,
        default: false,
        tokenPath: 'motion.enableParallax',
        description: 'Animated gradient background',
        testId: 'enable-parallax-checkbox',
    },
    {
        key: 'enableMagneticHover',
        type: 'boolean',
        label: 'Magnetic Hover',
        section: 'motion',
        subsection: 'Feature Flags',
        required: false,
        default: false,
        tokenPath: 'motion.enableMagneticHover',
        description: 'Buttons follow cursor',
        testId: 'enable-magnetic-hover-checkbox',
    },
    {
        key: 'enableScrollReveal',
        type: 'boolean',
        label: 'Scroll Reveal',
        section: 'motion',
        subsection: 'Feature Flags',
        required: false,
        default: false,
        tokenPath: 'motion.enableScrollReveal',
        description: 'Animate elements on scroll',
        testId: 'enable-scroll-reveal-checkbox',
    },

    // ===== MOTION - Durations =====
    {
        key: 'motionDurationInstant',
        type: 'number',
        label: 'Instant',
        section: 'motion',
        subsection: 'Durations (ms)',
        required: true,
        default: 0,
        tokenPath: 'motion.duration.instant',
        testId: 'motion-duration-instant-input',
        gridCols: 5,
    },
    {
        key: 'motionDurationFast',
        type: 'number',
        label: 'Fast',
        section: 'motion',
        subsection: 'Durations (ms)',
        required: true,
        default: 0,
        tokenPath: 'motion.duration.fast',
        testId: 'motion-duration-fast-input',
        gridCols: 5,
    },
    {
        key: 'motionDurationBase',
        type: 'number',
        label: 'Base',
        section: 'motion',
        subsection: 'Durations (ms)',
        required: true,
        default: 0,
        tokenPath: 'motion.duration.base',
        testId: 'motion-duration-base-input',
        gridCols: 5,
    },
    {
        key: 'motionDurationSlow',
        type: 'number',
        label: 'Slow',
        section: 'motion',
        subsection: 'Durations (ms)',
        required: true,
        default: 0,
        tokenPath: 'motion.duration.slow',
        testId: 'motion-duration-slow-input',
        gridCols: 5,
    },
    {
        key: 'motionDurationGlacial',
        type: 'number',
        label: 'Glacial',
        section: 'motion',
        subsection: 'Durations (ms)',
        required: true,
        default: 0,
        tokenPath: 'motion.duration.glacial',
        testId: 'motion-duration-glacial-input',
        gridCols: 5,
    },

    // ===== MOTION - Easing =====
    {
        key: 'motionEasingStandard',
        type: 'string',
        label: 'Standard',
        section: 'motion',
        subsection: 'Easing Curves',
        required: true,
        default: '',
        tokenPath: 'motion.easing.standard',
        placeholder: 'cubic-bezier(0.4, 0, 0.2, 1)',
        monospace: true,
        testId: 'motion-easing-standard-input',
        gridCols: 2,
    },
    {
        key: 'motionEasingDecelerate',
        type: 'string',
        label: 'Decelerate',
        section: 'motion',
        subsection: 'Easing Curves',
        required: true,
        default: '',
        tokenPath: 'motion.easing.decelerate',
        placeholder: 'cubic-bezier(0, 0, 0.2, 1)',
        monospace: true,
        testId: 'motion-easing-decelerate-input',
        gridCols: 2,
    },
    {
        key: 'motionEasingAccelerate',
        type: 'string',
        label: 'Accelerate',
        section: 'motion',
        subsection: 'Easing Curves',
        required: true,
        default: '',
        tokenPath: 'motion.easing.accelerate',
        placeholder: 'cubic-bezier(0.4, 0, 1, 1)',
        monospace: true,
        testId: 'motion-easing-accelerate-input',
        gridCols: 2,
    },
    {
        key: 'motionEasingSpring',
        type: 'string',
        label: 'Spring',
        section: 'motion',
        subsection: 'Easing Curves',
        required: true,
        default: '',
        tokenPath: 'motion.easing.spring',
        placeholder: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        monospace: true,
        testId: 'motion-easing-spring-input',
        gridCols: 2,
    },

    // ===== AURORA GRADIENT =====
    {
        key: 'auroraGradient',
        type: 'colorArray',
        label: 'Aurora Colors',
        section: 'aurora',
        required: false,
        default: [],
        tokenPath: 'semantics.colors.gradient.aurora',
        minColors: 2,
        maxColors: 4,
        testId: 'aurora-gradient',
    },

    // ===== GLASSMORPHISM =====
    {
        key: 'glassColor',
        type: 'rgba',
        label: 'Glass Color',
        section: 'glassmorphism',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.surface.glass',
        testId: 'glass-color-input',
        gridCols: 2,
    },
    {
        key: 'glassBorderColor',
        type: 'rgba',
        label: 'Glass Border',
        section: 'glassmorphism',
        required: false,
        default: '',
        tokenPath: 'semantics.colors.surface.glassBorder',
        testId: 'glass-border-color-input',
        gridCols: 2,
    },

    // ===== GRADIENTS =====
    {
        key: 'gradientPrimary',
        type: 'colorArray',
        label: 'Primary Gradient',
        section: 'glassmorphism',
        required: false,
        default: [],
        tokenPath: 'semantics.colors.gradient.primary',
        minColors: 2,
        maxColors: 2,
    },
    {
        key: 'gradientAccent',
        type: 'colorArray',
        label: 'Accent Gradient',
        section: 'glassmorphism',
        required: false,
        default: [],
        tokenPath: 'semantics.colors.gradient.accent',
        minColors: 2,
        maxColors: 2,
    },

    // ===== LEGAL =====
    {
        key: 'legalCompanyName',
        type: 'string',
        label: 'Company Name',
        section: 'legal',
        required: true,
        default: '',
        tokenPath: 'legal.companyName',
        placeholder: 'Acme Inc.',
    },
    {
        key: 'legalSupportEmail',
        type: 'string',
        label: 'Support Email',
        section: 'legal',
        required: true,
        default: '',
        tokenPath: 'legal.supportEmail',
        placeholder: 'support@example.com',
    },

    // ===== MARKETING =====
    {
        key: 'showMarketingContent',
        type: 'boolean',
        label: 'Show Marketing Content',
        section: 'marketing',
        required: false,
        default: true,
        tokenPath: '_marketingFlags.showMarketingContent',
        description: 'Display marketing pages and content',
    },
    {
        key: 'showPricingPage',
        type: 'boolean',
        label: 'Show Pricing Page',
        section: 'marketing',
        required: false,
        default: false,
        tokenPath: '_marketingFlags.showPricingPage',
        description: 'Display pricing page in navigation',
    },
] as const;

export function getFieldsBySection(sectionId: string): AnyFieldDef[] {
    return FIELD_REGISTRY.filter((f) => f.section === sectionId);
}

export function getRequiredFields(): AnyFieldDef[] {
    return FIELD_REGISTRY.filter((f) => f.required);
}
