import type { TenantData } from './types';

export const EMPTY_TENANT_DATA: TenantData = {
    tenantId: '',
    appName: '',
    domains: [],

    logoUrl: '',
    faviconUrl: '',

    primaryColor: '',
    primaryVariantColor: '',
    secondaryColor: '',
    secondaryVariantColor: '',
    accentColor: '',
    neutralColor: '',
    neutralVariantColor: '',
    successColor: '',
    warningColor: '',
    dangerColor: '',
    infoColor: '',

    surfaceBaseColor: '',
    surfaceRaisedColor: '',
    surfaceSunkenColor: '',
    surfaceOverlayColor: '',
    surfaceWarningColor: '',
    surfaceMutedColor: '',
    surfaceSubtleColor: '',
    surfacePopoverColor: '',

    textPrimaryColor: '',
    textSecondaryColor: '',
    textMutedColor: '',
    textInvertedColor: '',
    textAccentColor: '',

    interactivePrimaryColor: '',
    interactivePrimaryHoverColor: '',
    interactivePrimaryActiveColor: '',
    interactivePrimaryForegroundColor: '',
    interactiveSecondaryColor: '',
    interactiveSecondaryHoverColor: '',
    interactiveSecondaryActiveColor: '',
    interactiveSecondaryForegroundColor: '',
    interactiveAccentColor: '',
    interactiveDestructiveColor: '',
    interactiveDestructiveHoverColor: '',
    interactiveDestructiveActiveColor: '',
    interactiveDestructiveForegroundColor: '',
    interactiveGhostColor: '',
    interactiveMagneticColor: '',
    interactiveGlowColor: '',

    borderSubtleColor: '',
    borderDefaultColor: '',
    borderStrongColor: '',
    borderFocusColor: '',
    borderWarningColor: '',

    statusSuccessColor: '',
    statusWarningColor: '',
    statusDangerColor: '',
    statusInfoColor: '',

    fontFamilySans: '',
    fontFamilySerif: '',
    fontFamilyMono: '',

    typographySizeXs: '',
    typographySizeSm: '',
    typographySizeMd: '',
    typographySizeLg: '',
    typographySizeXl: '',
    typographySize2xl: '',
    typographySize3xl: '',
    typographySize4xl: '',
    typographySize5xl: '',

    fontWeightRegular: 0,
    fontWeightMedium: 0,
    fontWeightSemibold: 0,
    fontWeightBold: 0,

    lineHeightCompact: '',
    lineHeightStandard: '',
    lineHeightSpacious: '',

    letterSpacingTight: '',
    letterSpacingNormal: '',
    letterSpacingWide: '',

    typographySemanticBody: '',
    typographySemanticBodyStrong: '',
    typographySemanticCaption: '',
    typographySemanticButton: '',
    typographySemanticEyebrow: '',
    typographySemanticHeading: '',
    typographySemanticDisplay: '',

    spacing2xs: '',
    spacingXs: '',
    spacingSm: '',
    spacingMd: '',
    spacingLg: '',
    spacingXl: '',
    spacing2xl: '',

    spacingPagePadding: '',
    spacingSectionGap: '',
    spacingCardPadding: '',
    spacingComponentGap: '',

    radiiNone: '',
    radiiSm: '',
    radiiMd: '',
    radiiLg: '',
    radiiPill: '',
    radiiFull: '',

    shadowSm: '',
    shadowMd: '',
    shadowLg: '',

    legalCompanyName: '',
    legalSupportEmail: '',

    motionDurationInstant: 0,
    motionDurationFast: 0,
    motionDurationBase: 0,
    motionDurationSlow: 0,
    motionDurationGlacial: 0,

    motionEasingStandard: '',
    motionEasingDecelerate: '',
    motionEasingAccelerate: '',
    motionEasingSpring: '',

    enableParallax: false,
    enableMagneticHover: false,
    enableScrollReveal: false,

    showMarketingContent: true,
    showPricingPage: false,

    showAppNameInHeader: true,

    gradientPrimary: [],
    gradientAccent: [],
    auroraGradient: [],
    glassColor: '',
    glassBorderColor: '',

    // Derivation options
    derivationThemeMode: 'light',
    derivationStyle: 'balanced',
    derivationIntensity: 50,
};
